// Code generated by protoc-gen-go. DO NOT EDIT.
// This is a placeholder file. Run protoc to generate the actual code.
// See PROTO_SETUP.md for instructions.

package proto

import "context"

// Placeholder types - replace with actual generated code
type ScoredPostsQuery struct {
	ViewerId           int64
	ClientAppId        int32
	CountryCode        string
	LanguageCode       string
	SeenIds            []int64
	ServedIds          []int64
	InNetworkOnly      bool
	IsBottomRequest    bool
	BloomFilterEntries []*BloomFilterEntry
}

type BloomFilterEntry struct {
	Data []byte
}

type ScoredPostsResponse struct {
	ScoredPosts []*ScoredPost
}

type ScoredPost struct {
	TweetId               uint64
	AuthorId              uint64
	RetweetedTweetId      uint64
	RetweetedUserId       uint64
	InReplyToTweetId      uint64
	Score                 float32
	InNetwork             bool
	ServedType            int32
	LastScoredTimestampMs uint64
	PredictionRequestId   uint64
	Ancestors             []uint64
	ScreenNames           map[string]string
	VisibilityReason      string
}

// Placeholder service - replace with actual generated code
type ScoredPostsServiceServer interface {
	GetScoredPosts(ctx context.Context, req *ScoredPostsQuery) (*ScoredPostsResponse, error)
}

type UnimplementedScoredPostsServiceServer struct{}

func (UnimplementedScoredPostsServiceServer) GetScoredPosts(ctx context.Context, req *ScoredPostsQuery) (*ScoredPostsResponse, error) {
	return nil, nil
}

// RegisterScoredPostsServiceServer 注册服务（占位实现）
// 实际应该由 protoc-gen-go-grpc 生成
func RegisterScoredPostsServiceServer(s interface{}, srv ScoredPostsServiceServer) {
	// 占位实现，实际应该注册到 gRPC 服务器
}
