// Code generated by protoc-gen-go. DO NOT EDIT.
// This is a placeholder file for compilation purposes.
// To generate actual code, run: protoc --go_out=. --go-grpc_out=. in_network_posts.proto

package thunder

import (
	"context"
	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
)

// LightPost represents a lightweight post structure
type LightPost struct {
	PostID            int64
	AuthorID          int64
	CreatedAt         int64
	InReplyToPostID   *int64
	InReplyToUserID   *int64
	IsRetweet         bool
	IsReply           bool
	SourcePostID      *int64
	SourceUserID      *int64
	HasVideo          bool
	ConversationID    *int64
}

// TweetDeleteEvent represents a tweet deletion event
type TweetDeleteEvent struct {
	PostID    int64
	DeletedAt int64
}

// TweetCreateEvent represents a tweet creation event
type TweetCreateEvent struct {
	PostID            int64
	AuthorID          int64
	CreatedAt         int64
	InReplyToPostID   *int64
	InReplyToUserID   *int64
	IsRetweet         bool
	IsReply           bool
	SourcePostID      *int64
	SourceUserID      *int64
	HasVideo          bool
	ConversationID    *int64
}

// InNetworkEvent represents an in-network event (create or delete)
type InNetworkEvent struct {
	EventVariant interface{} // Can be *TweetCreateEvent or *TweetDeleteEvent
}

// GetInNetworkPostsRequest is the request for GetInNetworkPosts
type GetInNetworkPostsRequest struct {
	UserID           uint64
	FollowingUserIDs []uint64
	MaxResults       uint32
	ExcludeTweetIDs  []uint64
	Algorithm        string
	Debug            bool
	IsVideoRequest   bool
}

// GetInNetworkPostsResponse is the response for GetInNetworkPosts
type GetInNetworkPostsResponse struct {
	Posts []*LightPost
}

// InNetworkPostsServiceServer is the server interface for InNetworkPostsService
type InNetworkPostsServiceServer interface {
	GetInNetworkPosts(context.Context, *GetInNetworkPostsRequest) (*GetInNetworkPostsResponse, error)
}

// UnimplementedInNetworkPostsServiceServer must be embedded to have forward compatible implementations
type UnimplementedInNetworkPostsServiceServer struct{}

func (UnimplementedInNetworkPostsServiceServer) GetInNetworkPosts(context.Context, *GetInNetworkPostsRequest) (*GetInNetworkPostsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetInNetworkPosts not implemented")
}

// RegisterInNetworkPostsServiceServer registers the service server
// This is a placeholder - in real generated code this would properly register the service
func RegisterInNetworkPostsServiceServer(s *grpc.Server, srv InNetworkPostsServiceServer) {
	// Placeholder implementation - in real generated code this would register the service
	// For now, we'll use a simple approach: store the server implementation
	// In actual protoc-generated code, this would be handled automatically
	_ = srv
}
